spring:
  config:
    import: optional:file:.env[.properties]

server:
  port:
    8081

grpc:
  client:
    GLOBAL:
      address: ${GRPC_ADDRESS}
      negotiation-type: ${GRPC_NEGOTIATION_TYPE}

push:
  batch-size: ${BATCH_SIZE}